help:
	@echo "Please use \`make <target>' is one of"
	@echo "  compile       run sbt compile"
	@echo "  run           run sbt run"
	@echo "  test          run sbt test"
	@echo "  assembly      run sbt assembly"
	@echo "  console       run sbt console"
	@echo "  run_kz        run kafka & zookeeper"
	@echo "  stop_kz       stop kafka & zookeeper"
	@echo "  restart_kz    restart kafka & zookeeper"
	@echo "  make_topic    crate default topics"
	@echo "  delete_topics delete all topics"
	@echo "  k_status      show kafka status"
