name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests (kafka)
      run: cd kafka && sbt test
    - name: Compile (kafka)
      run: cd kafka && sbt assembly
      
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests (spark)
      run: cd spark-poc/sparkJob && sbt test
    - name: Compile (spark)
      run: cd spark-poc/sparkJob && sbt assembly
